// نصوص الكابينة. الصوت: العين تتكلم بصيغة المتكلم، جُمل قصيرة، لا وعود، وكل رقم تقديري يُسمّى تقديرًا.
import type {Lang} from '../i18n';
const ar={
 brand:'IKING',sim:'تجريبي · بيانات تمثيلية',
 simFoot:'تجريبي. لا بيانات حقيقية ولا إرسال لأي مشغّل. الطائرات والأوقات أمثلة توضيحية، والمسافات والأزمنة محسوبة من الإحداثيات.',
 phases:['على الأرض','صعود','تحليق','رحلتك','هبوط'],
 eye:{ask:'أنتظر وجهتك',understand:'أفهم رحلتك',search:'أبحث في السوق',found:'وجدتُ ما يستحق النظر',recommend:'أوصيك بخيار واحد',approve:'أحتاج موافقتك',waiting:'أنتظر ردّ المشغّل',confirmed:'تأكّد الطلب',monitor:'أراقب رحلتك',done:'اكتملت الرحلة'} as Record<string,string>,
 ask:{title:'إلى أين نأخذك؟',sub:'المس وجهتك على الرادار، أو مرّر إصبعك فوقه لأرى المسافة.',from:'من',to:'إلى',demo:'جرّب: 6 ضيوف من الرياض إلى لندن',tapTo:'اختر وجهتك',tapFrom:'اختر نقطة الانطلاق',change:'غيّر',
  read:(o:string,d:string,km:string,t:string)=>`${o} ← ${d} · ${km} كم · نحو ${t} (تقدير)`,here:(n:string)=>`${n} · أنت هنا`},
 und:{title:(o:string,d:string)=>`فهمتُ: ${o} إلى ${d}`,sub:'أحتاج أمرين فقط.',guests:'المسافرون',date:'التاريخ',when:'متى تفضّل أن تغادر؟',win:['صباحًا','ظهرًا','مساءً'],go:'ابدأ البحث',guestsUnit:(n:number)=>n===1?'ضيف':n===2?'ضيفان':n<=10?`${n} ضيوف`:`${n} ضيفًا`,
  big:'هذا العدد يحتاج ترتيبًا خاصًا. سأحوّل طلبك إلى وسيط بشري يتولاه معك.'},
 search:{title:'أبحث لك الآن',steps:['الطائرات القريبة','المسافة والمطارات','موقع الطائرات قبل الرحلة','الطقس'],later:'يُفحص عند تأكيد الرحلة',say:['أنظر إلى الطائرات حول','أحسب المسار','أتحقق من موقع الطائرات','أنتظر الطقس']},
 found:{title:'وجدتُ ثلاثة تستحق النظر',sub:'اختر أي واحد لأريك موقعه على الرادار.',evBtn:'اعرض الدليل',evTitle:'ما أعرفه، ومن أين',
  ev:{near:(n:number,o:string)=>`${n} طائرات مرصودة قرب ${o} وفي محيطها`,nearS:'تتبّع الطيران · محاكاة',op:'لم يؤكد أي مشغّل التوافر بعد',opS:'بانتظار الرد',route:(km:string,t:string)=>`المسافة ${km} كم، وزمن الطيران نحو ${t}`,routeS:'حساب من الإحداثيات',wx:'الطقس لم يُفحص بعد',wxS:'يُفحص عند التأكيد',clock:(c:string)=>`تتغير الساعة في ${c} في ذلك اليوم، وحسبتُ الوصول على التوقيت الجديد`,clockS:'قاعدة التوقيت'},
  st:{inferred:'استنتاج',unknown:'مجهول',estimated:'تقدير',pending:'قيد الانتظار',confirmed:'مؤكد'}},
 opt:{best:'الأنسب',value:'الأوفر',alt:'البديل',
  cat:{LIGHT:'خفيفة',MID:'متوسطة المقصورة',SUPER:'فوق المتوسطة',LARGE:'كبيرة المقصورة',ULR:'بعيدة المدى'} as Record<string,string>,
  bestD:(n:number,nonstop:boolean)=>nonstop?`رحلة بلا توقف، وتتسع لـ ${n} مع أمتعتهم.`:`تتسع لـ ${n} مع أمتعتهم، وقد تحتاج توقفًا قصيرًا للتزوّد.`,
  valueD:'قيمة أفضل بمساحة أقل.',altD:(m:number)=>`نفس الراحة، وتغادر بعد ${m} دقيقة.`,
  pos:(t:string)=>`تأتي من مكان آخر. التموضع نحو ${t} (تقدير)`,here:'موجودة في المدينة ولا تحتاج تموضعًا',
  status:'التوافر بانتظار تأكيد المشغّل',price:'السعر من المشغّل',at:(a:string,b:string)=>`تغادر ${a}، وتصل نحو ${b} (تقدير)`},
 rec:{lead:'أنصحك بالأول.',because:(o:string)=>`لأنه أنسب توازن بين المدى والراحة وموعدك. ${o}`,why:'ليه؟',whyT:'كيف اخترتُ',
  w:(best:string)=>[`المدى: ${best} تكفي المسافة كاملة`,'الراحة: مقصورة تتسع لمجموعتك مع حقائبها','الموعد: تلتقي مع الوقت الذي فضّلتَه بأقل انتظار','ما لا أعرفه بعد: التوافر والسعر، ويؤكدهما المشغّل وحده'],
  pick:'أوصني بواحد',cta:'اطلب تأكيد التوافر',other:'اعرض الخيارات الثلاثة'},
 appr:{title:'أحتاج موافقتك',body:'سأطلب من المشغّل تأكيد التوافر والسعر لهذه الرحلة.',note:'هذا طلب تأكيد وليس حجزًا. لا التزام مالي قبل أن توافق على عرض المشغّل.',ok:'أوافق',hold:'اضغط مطوّلًا للموافقة',holdKey:'أو اضغط Enter مرة واحدة',back:'ارجع'},
 wait:{title:'سجّلتُ رغبتك',body:'طلبتُ تأكيد التوافر من المشغّل. أبلغك أول ما يرد، وأؤكد معك التفاصيل بعدها.',st:'بانتظار ردّ المشغّل',sim:'محاكاة: ردّ المشغّل الآن',edit:'عدّل طلبي'},
 conf:{title:'تم التأكيد',body:(c:string)=>`أكّد المشغّل التوافر لطائرة ${c}. السعر يصلك مع عرضه المكتوب قبل أي التزام.`,ev:'أكّده المشغّل · مصدر: ردّ المشغّل (محاكاة)',price:'السعر: مع عرض المشغّل المكتوب',cta:'تابع رحلتي'},
 mon:{title:'أنت في أيدٍ أمينة',stages:['في الانتظار','تتجه إلى مطار الانطلاق','على الأرض','في الجو','تقترب من الوصول','وصلت'],
  say:(s:string,t:string)=>`${s}. وصولك المتوقع نحو ${t}.`,calm:'لا شيء يحتاج انتباهك الآن.',scrub:'حرّك الوقت لتتابع الرحلة',
  sim:'محاكاة',simChange:'ظهر خيار أفضل',simAlert:'تنبيه طقس',
  tl:['السيارة','المطار','الطائرة','الوصول','السيارة عند الوصول']},
 chg:{title:'وجدتُ خيارًا أفضل',body:'تغادر قبل 90 دقيقة، وتصل أبكر بالقدر نفسه.',diff:'فرق السعر: بانتظار المشغّل',approve:'اعتمد التغيير',keep:'أبقِ الحالي',kept:'أبقيتُ خطتك كما هي.',did:'اعتمدتُ التغيير، وأطلب تأكيده من المشغّل.'},
 alt:{title:'تنبيه واحد',body:(d:string,a:string)=>`رصدتُ تراجعًا متوقعًا في الرؤية عند ${d} وقت الوصول. أنصحك بمطار قريب هو ${a}، حالته الجوية أفضل ويزيد الطريق بالسيارة قليلًا.`,note:'القرار النهائي للمشغّل والطاقم. لا يتغير شيء قبل موافقتك.',approve:'اعتمد المطار البديل',keep:'أبقِ الخطة',sim:'محاكاة: لا أرصاد حقيقية في هذا العرض',kept:'أبقيتُ الخطة وأواصل المراقبة.',did:'اعتمدتُ المطار البديل، وأطلب تأكيده من المشغّل.',alt:'مطار بديل'},
 done:{title:(d:string)=>`أهلًا في ${d}`,body:'وصلتَ. أرجو أن تكون الرحلة كما أردتها.',again:'رحلة أخرى',sum:'ملخص رحلتك'},
 gl:{radar:'رادار العين: المس مدينة لاختيارها',hit:(n:string)=>`اختر ${n}`},
 aircraft:{approx:(n:string)=>`طائرة قرب ${n}`,sim:'محاكاة'},
 units:{km:'كم',h:'س',m:'د'},
};
type C=typeof ar;
const en:C={
 brand:"IKING",sim:'Demo · sample data',
 simFoot:'Demo. No real data and nothing is sent to any operator. Aircraft and times are examples; distances and durations are computed from coordinates.',
 phases:['On the ground','Climb','Cruise','Your journey','Descent'],
 eye:{ask:'Waiting for your destination',understand:'Understanding your trip',search:'Checking the market',found:'Found something worth a look',recommend:'Recommending one option',approve:'I need your approval',waiting:"Waiting for the operator's reply",confirmed:'Request confirmed',monitor:'Watching your trip',done:'Trip complete'},
 ask:{title:'Where shall we take you?',sub:'Tap your destination on the radar, or drag across it to see the distance.',from:'From',to:'To',demo:'Try: 6 guests, Riyadh to London',tapTo:'Pick a destination',tapFrom:'Pick a departure point',change:'Change',
  read:(o,d,km,t)=>`${o} → ${d} · ${km} km · about ${t} (estimate)`,here:n=>`${n} · you are here`},
 und:{title:(o,d)=>`Got it: ${o} to ${d}`,sub:'I only need two things.',guests:'Guests',date:'Date',when:'When would you like to leave?',win:['Morning','Midday','Evening'],go:'Start searching',guestsUnit:n=>n===1?'guest':`${n} guests`,
  big:'A group this size needs special arrangements. I will hand your request to a human broker.'},
 search:{title:'Searching for you',steps:['Aircraft nearby','Distance and airports','Aircraft position before the trip','Weather'],later:'Checked when the trip is confirmed',say:['Looking at aircraft around','Working out the route','Checking where aircraft are','Waiting on weather']},
 found:{title:'I found three worth considering',sub:'Pick any to see where it is on the radar.',evBtn:'View evidence',evTitle:'What I know, and from where',
  ev:{near:(n,o)=>`${n} aircraft seen near ${o} and around it`,nearS:'Flight tracking · simulated',op:'No operator has confirmed availability yet',opS:'Awaiting reply',route:(km,t)=>`Distance ${km} km, flight time about ${t}`,routeS:'Computed from coordinates',wx:'Weather not checked yet',wxS:'Checked at confirmation',clock:c=>`Clocks change in ${c} that day, and I calculated arrival on the new time`,clockS:'Time-zone rules'},
  st:{inferred:'Inferred',unknown:'Unknown',estimated:'Estimate',pending:'Pending',confirmed:'Confirmed'}},
 opt:{best:'Best match',value:'Best value',alt:'Alternative',
  cat:{LIGHT:'Light jet',MID:'Midsize cabin',SUPER:'Super-midsize',LARGE:'Large cabin',ULR:'Long range'},
  bestD:(n,nonstop)=>nonstop?`Nonstop, seats ${n} with their luggage.`:`Seats ${n} with luggage; may need a short fuel stop.`,
  valueD:'Better value, less space.',altD:m=>`Same comfort, departs ${m} minutes later.`,
  pos:t=>`Comes from elsewhere. Positioning about ${t} (estimate)`,here:'Already in the city, no positioning needed',
  status:'Availability awaiting operator confirmation',price:'Price comes from the operator',at:(a,b)=>`Departs ${a}, arrives about ${b} (estimate)`},
 rec:{lead:'I recommend the first.',because:o=>`It balances range, comfort and your schedule best. ${o}`,why:'Why?',whyT:'How I chose',
  w:best=>[`Range: ${best} covers the whole distance`,'Comfort: a cabin that fits your group and their bags','Timing: closest to the time you preferred, with the least waiting','What I do not know yet: availability and price, which only the operator can confirm'],
  pick:'Recommend one',cta:'Request availability',other:'Show all three'},
 appr:{title:'I need your approval',body:'I will ask the operator to confirm availability and price for this trip.',note:'This is a confirmation request, not a booking. No financial commitment until you accept the operator\u2019s offer.',ok:'Approve',hold:'Press and hold to approve',holdKey:'Or press Enter once',back:'Go back'},
 wait:{title:'Your request is logged',body:'I asked the operator to confirm availability. I will tell you the moment they reply, then confirm the details with you.',st:'Awaiting operator reply',sim:'Demo: operator replies now',edit:'Edit my request'},
 conf:{title:'Confirmed',body:c=>`The operator confirmed availability for a ${c}. The price arrives with their written offer before any commitment.`,ev:'Confirmed by operator · source: operator reply (demo)',price:"Price: with the operator's written offer",cta:'Follow my trip'},
 mon:{title:'You are in good hands',stages:['Waiting','Heading to departure airport','On the ground','In the air','Approaching arrival','Arrived'],
  say:(s,t)=>`${s}. Expected arrival about ${t}.`,calm:'Nothing needs your attention right now.',scrub:'Move time to follow the trip',
  sim:'Demo',simChange:'A better option appeared',simAlert:'Weather alert',
  tl:['Car','Airport','Aircraft','Arrival','Car on arrival']},
 chg:{title:'I found a better option',body:'It departs 90 minutes earlier and arrives that much sooner.',diff:'Price difference: awaiting operator',approve:'Approve change',keep:'Keep current',kept:'I kept your plan as it is.',did:'Change approved. I am asking the operator to confirm it.'},
 alt:{title:'One alert',body:(d,a)=>`I expect visibility to drop at ${d} around your arrival. I suggest a nearby airport, ${a}: better conditions, slightly longer drive.`,note:'The final decision belongs to the operator and crew. Nothing changes without your approval.',approve:'Approve alternate airport',keep:'Keep plan',sim:'Demo: no real weather data in this preview',kept:'Plan kept. I will keep watching.',did:'Alternate airport approved. I am asking the operator to confirm it.',alt:'Alternate airport'},
 done:{title:d=>`Welcome to ${d}`,body:'You have arrived. I hope the trip was what you wanted.',again:'Another trip',sum:'Your trip'},
 gl:{radar:'Eye radar: tap a city to choose it',hit:n=>`Choose ${n}`},
 aircraft:{approx:n=>`Aircraft near ${n}`,sim:'Demo'},
 units:{km:'km',h:'h',m:'m'},
};
export const copy=(l:Lang):C=>l==='ar'?ar:en;
export type Copy=C;
