import {getLang,useI18n,type Lang} from '../i18n';
// نصوص الواجهة الجديدة بعد الدخول (بيت العين). منفصلة عن القواميس الأصلية كي لا نلمسها.
type D=Record<string,string>;
const ar:D={
'greet':'صباح الخير','greet.sub':'راقبت شبكتك. هذا ما يحتاج انتباهك:','greet.none':'راقبت شبكتك. لا شيء يحتاج انتباهك الآن.',
'c.mission':'مهمة','c.opp':'فرصة','c.client':'عميل',
'c.mission.q':'لا توجد رحلة مؤكدة لمراقبتها بعد. تبدأ مراقبة الرحلة مع أول رحلة مؤكدة.',
'c.opp.pend':'{n} فرصة تنتظر موافقتك. لن يُرسل شيء لأي عميل قبل أن توافق.',
'c.opp.park':'{n} طائرة واقفة قربها إشارة طلب. الوقوف لا يعني أنها متاحة، والتأكيد من المشغّل.',
'c.opp.ev':'{n} إشارة فعالية خلال 14 يومًا. إشارات من مصادر عامة، وليست طلبات مؤكدة.',
'c.opp.q':'لا فرصة جديدة الآن.',
'c.client.n':'{n} طلب عميل مفتوح قرب طائرات واقفة.','c.client.q':'لا إشارة عميل الآن.',
'checked':'فحصتُ الآن: الفرص، والطائرات الواقفة، وتقويم الفعاليات.','checked.at':'الساعة {t}',
'checked.fail':'تعذّر فحص: {x}. لا أعرض هنا شيئًا عنه.',
'loading':'العين تراجع الشبكة…','badge.live':'بيانات حقيقية','badge.sim':'محاكاة',
'layers':'الطبقات تحت العين','l.opp':'عين الفرص','l.rev':'عين الإيراد','l.guard':'حارس الرحلة','l.file':'ملف الرحلة',
's.live':'تعمل بالبيانات الحالية','s.sim':'عرض تجريبي','s.wait':'تنتظر مشغّلًا أو عميلًا حقيقيًا',
'l.opp.d':'الطلب والفعاليات والفرص التي تنتظر قرارك.','l.rev.d':'الأسطول، والطائرات الواقفة، والرحلة الفاضية.',
'l.guard.d':'طقس المطارات موجود. يُربط برحلة مؤكدة مع أول رحلة، ثم يقترح بديلًا بموافقة إنسان.',
'l.file.d':'التفضيلات والذاكرة والباب للباب. تبدأ مع أول عميل حقيقي، ولا نحفظ إلا ما يقوله العميل بنفسه.',
'st.noticed':'لاحظتُ','st.why':'لماذا يهم','st.checked':'راجعتُ','st.rec':'أوصي','st.approve':'اضغط مطوّلًا للموافقة','st.draft':'المسودة جاهزة. لم يُرسل شيء.',
'day.title':'يوم في حياة العين','day.lead':'عرض تجريبي من الصباح إلى الليل: كيف تلاحظ العين وتفحص وتوصي، وأنت تقرر.',
'day.run':'شغّل اليوم','day.rerun':'أعد اليوم','day.sim':'محاكاة. لا بيانات حقيقية ولا إرسال.','day.pick':'اختر وقتًا',
'why.title':'أسباب التوصية','l.broker':'غرفة الوسيط','l.broker.d':'داخلية للموظفين. القرارات المنتظرة ومقارنة العروض وما يراه كل طرف.',
'tone.opp':'فرصة','tone.watch':'مراقبة','tone.risk':'انتباه','tone.calm':'هادئ',
};
const en:D={
'greet':'Good morning','greet.sub':'I watched your network. This needs your attention:','greet.none':'I watched your network. Nothing needs your attention right now.',
'c.mission':'Mission','c.opp':'Opportunity','c.client':'Client',
'c.mission.q':'No confirmed trip to watch yet. Trip watching starts with the first confirmed trip.',
'c.opp.pend':'{n} opportunities wait for your approval. Nothing is sent to any customer until you approve.',
'c.opp.park':'{n} parked aircraft near a demand signal. Parked does not mean available; the operator confirms.',
'c.opp.ev':'{n} event signals within 14 days. Public-source signals, not confirmed requests.',
'c.opp.q':'No new opportunity right now.',
'c.client.n':'{n} open customer requests near parked aircraft.','c.client.q':'No customer signal right now.',
'checked':'Just checked: opportunities, parked aircraft and the event calendar.','checked.at':'at {t}',
'checked.fail':'Could not check: {x}. Nothing is shown about it here.',
'loading':'The Eye is reviewing the network…','badge.live':'LIVE DATA','badge.sim':'SIM',
'layers':'Layers under the Eye','l.opp':'Opportunity eye','l.rev':'Revenue eye','l.guard':'Trip guard','l.file':'Trip file',
's.live':'Running on current data','s.sim':'Demo view','s.wait':'Waiting for a real operator or customer',
'l.opp.d':'Demand, events and opportunities waiting for your decision.','l.rev.d':'Fleet, parked aircraft and the empty leg.',
'l.guard.d':'Airport weather is stored. It links to a confirmed trip once one exists, then suggests an alternative for a human to approve.',
'l.file.d':'Preferences, memory and door to door. Starts with the first real customer, and only saves what the customer says themselves.',
'st.noticed':'What I noticed','st.why':'Why it matters','st.checked':'What I checked','st.rec':'What I recommend','st.approve':'Press and hold to approve','st.draft':'Draft ready. Nothing was sent.',
'day.title':'A day in the life of the Eye','day.lead':'A demo from morning to night: how the Eye notices, checks and recommends, while you decide.',
'day.run':'Play the day','day.rerun':'Replay the day','day.sim':'Simulation. No real data and nothing is sent.','day.pick':'Pick a time',
'why.title':'Why this is recommended','l.broker':'Broker room','l.broker.d':'Internal, for staff. Pending decisions, quote comparison and what each side sees.',
'tone.opp':'Opportunity','tone.watch':'Watching','tone.risk':'Attention','tone.calm':'Calm',
};
const tr:D={
'greet':'Günaydın','greet.sub':'Ağınızı izledim. Dikkatinizi gerektirenler:','greet.none':'Ağınızı izledim. Şu an dikkatinizi gerektiren bir şey yok.',
'c.mission':'Görev','c.opp':'Fırsat','c.client':'Müşteri',
'c.mission.q':'İzlenecek onaylı bir uçuş henüz yok. Uçuş takibi ilk onaylı uçuşla başlar.',
'c.opp.pend':'{n} fırsat onayınızı bekliyor. Siz onaylamadan hiçbir müşteriye bir şey gönderilmez.',
'c.opp.park':'Talep sinyali yakınında {n} park halinde uçak var. Park halinde olmak müsait olduğu anlamına gelmez; onay operatörden gelir.',
'c.opp.ev':'14 gün içinde {n} etkinlik sinyali. Açık kaynaklı sinyaller, onaylı talep değil.',
'c.opp.q':'Şu an yeni fırsat yok.',
'c.client.n':'Park halindeki uçaklar yakınında {n} açık müşteri talebi.','c.client.q':'Şu an müşteri sinyali yok.',
'checked':'Az önce kontrol ettim: fırsatlar, park halindeki uçaklar ve etkinlik takvimi.','checked.at':'saat {t}',
'checked.fail':'Kontrol edilemedi: {x}. Burada bu konuda bir şey gösterilmiyor.',
'loading':'Göz ağı gözden geçiriyor…','badge.live':'GERÇEK VERİ','badge.sim':'SİM',
'layers':'Gözün altındaki katmanlar','l.opp':'Fırsat gözü','l.rev':'Gelir gözü','l.guard':'Uçuş koruyucusu','l.file':'Uçuş dosyası',
's.live':'Mevcut verilerle çalışıyor','s.sim':'Demo görünümü','s.wait':'Gerçek bir operatör veya müşteri bekleniyor',
'l.opp.d':'Talep, etkinlikler ve kararınızı bekleyen fırsatlar.','l.rev.d':'Filo, park halindeki uçaklar ve boş bacak.',
'l.guard.d':'Havalimanı hava durumu kayıtlı. Onaylı bir uçuş olunca ona bağlanır, sonra bir insanın onaylayacağı alternatif önerir.',
'l.file.d':'Tercihler, hafıza ve kapıdan kapıya. İlk gerçek müşteriyle başlar ve yalnızca müşterinin kendi söylediklerini kaydeder.',
'st.noticed':'Fark ettiğim','st.why':'Neden önemli','st.checked':'Kontrol ettiğim','st.rec':'Önerim','st.approve':'Onaylamak için basılı tutun','st.draft':'Taslak hazır. Hiçbir şey gönderilmedi.',
'day.title':'Gözün bir günü','day.lead':'Sabahtan geceye bir demo: Göz nasıl fark eder, kontrol eder ve önerir; karar sizin.',
'day.run':'Günü oynat','day.rerun':'Günü tekrar oynat','day.sim':'Simülasyon. Gerçek veri yok, hiçbir şey gönderilmez.','day.pick':'Bir saat seçin',
'why.title':'Önerinin nedenleri','l.broker':'Komisyoncu odası','l.broker.d':'Personele özel, dahili. Bekleyen kararlar, teklif karşılaştırması ve her tarafın gördüğü.',
'tone.opp':'Fırsat','tone.watch':'İzleme','tone.risk':'Dikkat','tone.calm':'Sakin',
};
const ru:D={
'greet':'Доброе утро','greet.sub':'Я наблюдал за вашей сетью. Вот что требует внимания:','greet.none':'Я наблюдал за вашей сетью. Сейчас ничто не требует вашего внимания.',
'c.mission':'Рейс','c.opp':'Возможность','c.client':'Клиент',
'c.mission.q':'Подтверждённого рейса для наблюдения пока нет. Наблюдение начнётся с первого подтверждённого рейса.',
'c.opp.pend':'Возможностей, ожидающих вашего одобрения: {n}. Ничего не уйдёт клиенту, пока вы не одобрите.',
'c.opp.park':'Самолётов на стоянке рядом с сигналом спроса: {n}. Стоянка не значит «доступен»; подтверждает оператор.',
'c.opp.ev':'Сигналов о событиях в ближайшие 14 дней: {n}. Это сигналы из открытых источников, а не подтверждённые запросы.',
'c.opp.q':'Новых возможностей сейчас нет.',
'c.client.n':'Открытых запросов клиентов рядом с самолётами на стоянке: {n}.','c.client.q':'Сигналов от клиентов сейчас нет.',
'checked':'Только что проверил: возможности, самолёты на стоянке и календарь событий.','checked.at':'в {t}',
'checked.fail':'Не удалось проверить: {x}. Здесь о нём ничего не показываю.',
'loading':'Глаз просматривает сеть…','badge.live':'РЕАЛЬНЫЕ ДАННЫЕ','badge.sim':'СИМ',
'layers':'Слои под Глазом','l.opp':'Глаз возможностей','l.rev':'Глаз дохода','l.guard':'Страж рейса','l.file':'Досье рейса',
's.live':'Работает на текущих данных','s.sim':'Демонстрация','s.wait':'Ждёт реального оператора или клиента',
'l.opp.d':'Спрос, события и возможности, ждущие вашего решения.','l.rev.d':'Флот, самолёты на стоянке и пустой рейс.',
'l.guard.d':'Погода аэропортов сохранена. С первым подтверждённым рейсом она привяжется к нему и предложит запасной вариант, который одобряет человек.',
'l.file.d':'Предпочтения, память и «от двери до двери». Начнётся с первого реального клиента и сохранит только то, что клиент сказал сам.',
'st.noticed':'Что я заметил','st.why':'Почему это важно','st.checked':'Что я проверил','st.rec':'Что рекомендую','st.approve':'Удерживайте для одобрения','st.draft':'Черновик готов. Ничего не отправлено.',
'day.title':'День из жизни Глаза','day.lead':'Демонстрация от утра до ночи: как Глаз замечает, проверяет и рекомендует, а решаете вы.',
'day.run':'Запустить день','day.rerun':'Повторить день','day.sim':'Симуляция. Нет реальных данных, ничего не отправляется.','day.pick':'Выберите время',
'why.title':'Почему это рекомендуется','l.broker':'Комната брокера','l.broker.d':'Внутренняя, для сотрудников. Ожидающие решения, сравнение предложений и что видит каждая сторона.',
'tone.opp':'Возможность','tone.watch':'Наблюдение','tone.risk':'Внимание','tone.calm':'Спокойно',
};
const D:Record<Lang,D>={ar,en,tr,ru};
const fill=(s:string,v?:Record<string,string|number>)=>{if(v)for(const x in v)s=s.split(`{${x}}`).join(String(v[x]));return s};
export const cp=(k:string,v?:Record<string,string|number>)=>fill(D[getLang()][k]??D.en[k]??k,v);
export const useCopy=()=>{const {lang}=useI18n();void lang;return cp};
export const dayLang=()=>getLang();
